#!/usr/bin/env bash

# fix portage dir tree
mkdir -p /etc/portage/package/unmask/
mkdir -p /etc/portage/package/mask/
mkdir -p /etc/portage/profile
touch /etc/portage/package.use


# USE and Profile
source /etc/portage/make.conf
sed -r "s/^USE=.*$/USE='-systemd openrc-force ${USE}'/" /etc/portage/make.conf
echo '-openrc-force' > /etc/portage/profile/use.mask


# Layman
emerge -va layman
layman -S

cat << 'EOF' >> /etc/portage/make.conf

# Layman
source /var/lib/layman/make.conf
EOF

layman -a gnome


# unmask
cat << 'EOF' > /etc/portage/package/unmask/gnome-3.12
<app-accessibility/accerciser-3.13
<app-accessibility/orca-3.13
<app-cdr/brasero-3.13
<app-crypt/gcr-3.13
<app-dicts/gnome-dictionary-3.13.0
<app-editors/ghex-3.13
<app-misc/bijiben-3.13
<app-misc/gnote-3.13
<dev-libs/gdl-3.13
<dev-libs/seed-3.13
<dev-python/pygobject-3.13
<dev-util/anjuta-3.13
<dev-util/devhelp-3.13
<dev-util/gnome-devel-docs-3.13
<gnome-base/gdm-3.13
<gnome-base/gnome-3.13
<gnome-base/gnome-common-3.13.0
<gnome-base/gnome-control-center-3.13
<gnome-base/gnome-core-apps-3.13.0
<gnome-base/gnome-core-libs-3.13.0
<gnome-base/gnome-desktop-3.13
<gnome-base/gnome-extra-apps-3.13.0
<gnome-base/gnome-fallback-3.13.0
<gnome-base/gnome-keyring-3.13
<gnome-base/gnome-light-3.13
<gnome-base/gnome-menus-3.13
<gnome-base/gnome-session-3.13
<gnome-base/gnome-settings-daemon-3.13
<gnome-base/gnome-shell-3.13
<gnome-base/gsettings-desktop-schemas-3.13
<gnome-base/libgnome-keyring-3.13
<gnome-base/nautilus-3.13
<gnome-extra/evolution-data-server-3.13
<gnome-extra/evolution-ews-3.13
<gnome-extra/evolution-kolab-3.13
<gnome-extra/gnome-calculator-3.13
<gnome-extra/gnome-clocks-3.13
<gnome-extra/gnome-color-manager-3.13
<gnome-extra/gnome-contacts-3.13
<gnome-extra/gnome-documents-3.13
<gnome-extra/gnome-getting-started-docs-3.13
<gnome-extra/gnome-power-manager-3.13
<gnome-extra/gnome-shell-extensions-3.13
<gnome-extra/gnome-system-monitor-3.13
<gnome-extra/gnome-user-docs-3.13
<gnome-extra/gnome-user-share-3.13
<gnome-extra/gnome-weather-3.13
<gnome-extra/gucharmap-3.13
<gnome-extra/mousetweaks-3.13
<gnome-extra/sushi-3.13
<gnome-extra/yelp-3.13
<gnome-extra/yelp-xsl-3.13
<gnome-extra/zenity-3.13
<mail-client/evolution-3.13
<media-gfx/eog-3.13
<media-gfx/eog-plugins-3.13
<media-gfx/gnome-font-viewer-3.13
<media-gfx/gnome-photos-3.13
<media-gfx/gnome-screenshot-3.13
<media-video/totem-3.13
<net-im/empathy-3.13
<net-misc/vinagre-3.13
<sys-apps/gnome-disk-utility-3.13
<www-client/epiphany-3.13
<x11-libs/gtksourceview-3.13
<x11-libs/libcryptui-3.13
<x11-libs/libwnck-3.13
<x11-misc/alacarte-3.13.0
<x11-terms/gnome-terminal-3.13
<x11-themes/gnome-backgrounds-3.13
<x11-themes/gnome-icon-theme-3.13
<x11-themes/gnome-icon-theme-symbolic-3.13
<x11-themes/gnome-themes-standard-3.13
<x11-wm/mutter-3.13
games-arcade/gnome-robots
games-board/four-in-a-row
games-board/gnome-chess
games-board/gnome-mines
games-board/iagno
games-puzzle/five-or-more
games-puzzle/gnome-klotski
games-puzzle/gnome-sudoku
games-puzzle/gnome-tetravex
games-puzzle/quadrapassel
games-puzzle/swell-foop
EOF


# mask
cat << 'EOF' > /etc/portage/package/mask/gnome-3.13
>=app-accessibility/accerciser-3.13
>=app-accessibility/orca-3.13
>=app-cdr/brasero-3.13
>=app-crypt/gcr-3.13
>=app-dicts/gnome-dictionary-3.13.0
>=app-editors/ghex-3.13
>=app-misc/bijiben-3.13
>=app-misc/gnote-3.13
>=dev-libs/gdl-3.13
>=dev-libs/seed-3.13
>=dev-python/pygobject-3.13
>=dev-util/anjuta-3.13
>=dev-util/devhelp-3.13
>=dev-util/gnome-devel-docs-3.13
>=gnome-base/gdm-3.13
>=gnome-base/gnome-3.13
>=gnome-base/gnome-common-3.13.0
>=gnome-base/gnome-control-center-3.13
>=gnome-base/gnome-core-apps-3.13.0
>=gnome-base/gnome-core-libs-3.13.0
>=gnome-base/gnome-desktop-3.13
>=gnome-base/gnome-extra-apps-3.13.0
>=gnome-base/gnome-fallback-3.13.0
>=gnome-base/gnome-keyring-3.13
>=gnome-base/gnome-light-3.13
>=gnome-base/gnome-menus-3.13
>=gnome-base/gnome-session-3.13
>=gnome-base/gnome-settings-daemon-3.13
>=gnome-base/gnome-shell-3.13
>=gnome-base/gsettings-desktop-schemas-3.13
>=gnome-base/libgnome-keyring-3.13
>=gnome-base/nautilus-3.13
>=gnome-extra/evolution-data-server-3.13
>=gnome-extra/evolution-ews-3.13
>=gnome-extra/evolution-kolab-3.13
>=gnome-extra/gnome-calculator-3.13
>=gnome-extra/gnome-clocks-3.13
>=gnome-extra/gnome-color-manager-3.13
>=gnome-extra/gnome-contacts-3.13
>=gnome-extra/gnome-documents-3.13
>=gnome-extra/gnome-getting-started-docs-3.13
>=gnome-extra/gnome-power-manager-3.13
>=gnome-extra/gnome-shell-extensions-3.13
>=gnome-extra/gnome-system-monitor-3.13
>=gnome-extra/gnome-user-docs-3.13
>=gnome-extra/gnome-user-share-3.13
>=gnome-extra/gnome-weather-3.13
>=gnome-extra/gucharmap-3.13
>=gnome-extra/mousetweaks-3.13
>=gnome-extra/sushi-3.13
>=gnome-extra/yelp-3.13
>=gnome-extra/yelp-xsl-3.13
>=gnome-extra/zenity-3.13
>=mail-client/evolution-3.13
>=media-gfx/eog-3.13
>=media-gfx/eog-plugins-3.13
>=media-gfx/gnome-font-viewer-3.13
>=media-gfx/gnome-photos-3.13
>=media-gfx/gnome-screenshot-3.13
>=media-video/totem-3.13
>=net-im/empathy-3.13
>=net-misc/vinagre-3.13
>=sys-apps/gnome-disk-utility-3.13
>=www-client/epiphany-3.13
>=x11-libs/gtksourceview-3.13
>=x11-libs/libcryptui-3.13
>=x11-libs/libwnck-3.13
>=x11-misc/alacarte-3.13.0
>=x11-terms/gnome-terminal-3.13
>=x11-themes/gnome-backgrounds-3.13
>=x11-themes/gnome-icon-theme-3.13
>=x11-themes/gnome-icon-theme-symbolic-3.13
>=x11-themes/gnome-themes-standard-3.13
>=x11-wm/mutter-3.13
EOF

# mask telepathy
cat << 'EOF' > /etc/portage/package/mask/telepathy-mission-control
# We want to use the gnome version of this package.
net-im/telepathy-mission-control::gentoo
EOF

exit 0
